CREATE TABLE `utenti` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`cognome` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`email` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`login` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`password` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_bin'
ENGINE=MyISAM
AUTO_INCREMENT=2
;
